version: '2'

services:
  phpipam:
    image: hitsumabushi/phpipam
    ports: 
      - "80:80"
    environment:
      - MYSQL_DB_HOSTNAME=mariadb
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_USERNAME=phpipam
      - MYSQL_DB_PASSWORD=db_password
      - MYSQL_DB_NAME=phpipam
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_DATABASE=phpipam
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=db_password
    restart: always
    volumes:
      - phpipam-data-volume:/var/lib/mysql

volumes:
  phpipam-data-volume:
